[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-e",
    "-C", "link-arg=main",
    "-C", "panic=abort",
    "-C", "link-arg=-lgcc_eh",
]

